### ISSUE TITLE
Add logos of Digital Ocean, GitHub and Twilio to footer

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#1]
Add logos of Digital Ocean, GitHub and Twilio to the footer of the site

**Comment by daniloff200** [comment]
Hey :) I can help with that!

**Comment by JCass45** [comment]
Would be happy to take this one on for Hacktoberfest

**Comment by damcclean** [comment]
Feel free to make a PR :)

**Comment by damcclean** [comment]
Added in #3
