### ISSUE TITLE
Make grid mobile friendly

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#10]
Make the grid of results mobile friendly.

**Comment by indransyah** [comment]
Will doing it

**Comment by lucas-barros** [comment]
Is this available for work?

**Comment by damcclean** [comment]
Yep, no PRs for this yet. @lucas-barros

**Comment by damcclean** [comment]
This issue is still open if anyone wants to work on it 👍

**Comment by lucas-barros** [comment]
Hi @damcclean sorry for the delay, added the PR. Here is the PR preview: https://deploy-preview-18--hacktoberfest-finder.netlify.com/

**Comment by damcclean** [comment]
Awesome! I've merged your PR

**Comment by damcclean** [comment]
Fixed in #18
