### ISSUE TITLE
✨ Convert from SASS to PostCSS

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#110]
## Description
I don't really like Sass that much these days and I would prefer if the styles could be converted to PostCSS with a PostCSS nesting plugin.

**Comment by DiegoBousfield** [comment]
Can I take this issue?

**Comment by damcclean** [comment]
@DiegoBousfield Sure!

**Comment by DiegoBousfield** [comment]
I don't know if this is what you are looking for, but here #111 is my contribution. If there's something to change, please let me know

**Comment by damcclean** [comment]
You did the job. Closed by #111
