### ISSUE TITLE
✨ Make the header a bit nicer

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#113]
## Description
I'd like for the header to be a bit smaller and to require less screen estate. It should also include the filtering as part of the header (which should also be redesigned)

**Comment by kev1nboer** [comment]
Hi Duncan, I can take care of this. Are there any more requirements?

**Comment by damcclean** [comment]
> Hi Duncan, I can take care of this. Are there any more requirements?

Not really, although it should be mobile responsive.

**Comment by kev1nboer** [comment]
Alright. On it!

**Comment by passwordjr** [comment]
Is there any need for enhancement here?

**Comment by kev1nboer** [comment]
Added a PR: #115
