### ISSUE TITLE
✨ Update favicons for new Hacktoberfest branding

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#117]
## Description
The current favicon for the site is for the 2018 branding. However, it needs to be updated to this year's branding.

**Comment by audrius59** [comment]
Can I take this one?

**Comment by damcclean** [comment]
Sure! @audrius59

**Comment by divyhshah** [comment]
hello i taken this for further enhancement is any more improvement is needed from your side ?

**Comment by damcclean** [comment]
hey @divyhshah, you can take the issue if you want. All that we need to do is update the favicons on the site to the ones for the new Hacktoberfest 2019 branding.

This is the [favicon generator](https://realfavicongenerator.net/) that I normally use to generate favicon images.
