### ISSUE TITLE
✨ Filter issues by no replies

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#129]
## Description
It would be cool if there was a way to filter the issues so that we could find issues that don't have any replies on them.

**Comment by wooojek** [comment]
I can try to do this ;)

**Comment by vanya829** [comment]
This is one of the way to implement sorting by no replies. It's not a filter, but it general does the same, if you sort buy asc.

**Comment by wooojek** [comment]
from what I see you are fetching the data again, I don't think it's necessary

**Comment by vanya829** [comment]
@wooojek Request fetch only first 30 items. So you have to do extra fetch to apply sorting. Otherwise you will sort items of the first page only

**Comment by wooojek** [comment]
@vanya829 what we can do is to merge filtering with fetching sorted data to be sure that you only show no replies issues

**Comment by vanya829** [comment]
If sorting is not, what expected. Can rebuild it to filter. It's easy to do, just add to request query "comments:0"

**Comment by wooojek** [comment]
@vanya829 sounds good :)
