### ISSUE TITLE
✨ Local Development Server

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#131]
## Description
I would like it if we could add some sort of local development server that watches Laravel Mix and also serves the `index.html` to `localhost`.

**Comment by wooojek** [comment]
what about script command `hot`?

**Comment by damcclean** [comment]
> what about script command `hot`?

Sorry what do you mean?

**Comment by wooojek** [comment]
there's command in package.json, you can run it with `yarn run hot` or `npm run hot`, it invokes webpack-dev-server, that serves files to localhost:8080, isn't that what you want?

**Comment by damcclean** [comment]
ah, didn't realise that was there! thanks
