### ISSUE TITLE
🐛 Fix issues where text does not fit in card

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#135]
## Describe the bug
Some issue titles are too big for the cards. I think we might need to shorten them if they get too big..

## Screenshots
![image](https://user-images.githubusercontent.com/19637309/66072144-64a01a00-e54c-11e9-9289-8c40393baef9.png)

**Comment by NeonNature** [comment]
May I take this issue please?

**Comment by damcclean** [comment]
> May I take this issue please?

Sure!

**Comment by NeonNature** [comment]
Seems there's a pull request now. I didn't get to finish last night. ^^'
