### ISSUE TITLE
🐛 Emojis on labels are too big

### ISSUE THREAD

**Issue by xeBuz** [damcclean/hacktoberfest-finder#151]
## Describe the bug
When a label has an emoji, it looks big

## Steps to reproduce
1. Just open the main site, some luck needed. Or edit the HTML to force an emoji :wink:

## Expected behavior
Emoji size should follow text size

## Screenshots
![image](https://user-images.githubusercontent.com/662916/66765920-2b9d6900-eead-11e9-8657-fb26497a939a.png)

**Comment by ferrl** [comment]
I can open a PR for this one. 👍

**Comment by xeBuz** [comment]
@ferrl Sorry, I found out it was easy to fix, so I made a quick PR while I'm working on a different issue :(
