### ISSUE TITLE
Fix text going out of box

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#16]
![https://cdn-std.dprcdn.net/files/acc_635918/aVXsaC](https://cdn-std.dprcdn.net/files/acc_635918/aVXsaC)

Fix it so that text does not go outside the white boxes.

**Comment by MattMcCherry** [comment]
Will do this, easy fix 👍

**Comment by damcclean** [comment]
Awesome @MattMcCherry, thanks 👍

**Comment by damcclean** [comment]
Fixed in #17
