### ISSUE TITLE
Refreshed Design

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#176]
My plan for this year is to re-create the 'Hacktoberfest Finder' design. Ideally, I'd like to make it something cleaner, and easier to filter through by language.

Feel free to start with a fresh codebase and just move over the parts of JavaScript that's needed.

Although, there's a few technologies I'd like to use:
* [Tailwind CSS](https://tailwindcss.com)
* [Alpine.js](https://github.com/alpinejs/alpine) - this would be instead of Vue

I'm happy for people to bounce around any ideas they have on here.

**Comment by HIMANKARLIS** [comment]
@damcclean would you like to have a ui design for that?

**Comment by damcclean** [comment]
In fact, I've come up with a design... I'll try and get it out over the next few hours and create some issues.

**Comment by HIMANKARLIS** [comment]
@damcclean OK 👍🏻
