### ISSUE TITLE
Make Filters Functional

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#179]
I've just redesigned the [Hacktoberfest Finder](https://hacktoberfest-finder.netlify.app/) site, in the process though I've broken some of the filtering functionality.

I'd appreciate it if someone could have a look at fixing the language filter and the sorting filter.

**Comment by jmoranin98** [comment]
I would like to work on this issue

**Comment by jimbo8098** [comment]
I'm seeing the same issue in Chromimum v85.0.4183.121

**Comment by BetaHuhn** [comment]
Hey, I'd like to work on this issue, can you assign me?

**Comment by damcclean** [comment]
> Hey, I'd like to work on this issue, can you assign me?

Done!

**Comment by BetaHuhn** [comment]
@damcclean Please review the [PR](https://github.com/damcclean/hacktoberfest-finder/pull/190)
