### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#180]
This project hasn't really been worked on since last October so all of the NPM dependencies are out-of-date. 

I'd appreciate it if someone could update the dependencies so we can take advantage of the latest features and security updates. Thanks!

**Comment by Zach128** [comment]
Hi @damcclean. I'd be happy to work on it. Would you like I'll take on the issue?

**Comment by damcclean** [comment]
> Hi @damcclean. I'd be happy to work on it. Would you like I'll take on the issue?

Sure!

**Comment by Zach128** [comment]
Great. I'll keep you updated on my progress/issues I encounter.

**Comment by damcclean** [comment]
@Zach128 Looks like someone else has bet you to it, #182.

**Comment by Zach128** [comment]
No worries.
