### ISSUE TITLE
Only show issues for current year

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#187]
I think it would make sense for the app to automatically filter out issues that were not created in the current year.

**Comment by Shaddamah** [comment]
I'd like to resolve this issue, can you assign me?

**Comment by BetaHuhn** [comment]
Hey, could I also work in this? Seems like a quick fix.

**Comment by damcclean** [comment]
> Hey, could I also work in this? Seems like a quick fix.

Sure!!

**Comment by BetaHuhn** [comment]
Should it only filter out issues created this year or also issues which where updated this year?

**Comment by damcclean** [comment]
It should only show issues created this year.

So an issue from last year shouldn't show where as one created this year should be shown.

**Comment by Shaddamah** [comment]
Oh i'm about to fix it, but okay. Great job! @BetaHuhn
This issue should be closed i guess
