### ISSUE TITLE
Add a loading state

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#188]
It would be nice if we could add a loading state while the issues are loading in instead of it just being white space.

**Comment by Spoon-8285** [comment]
hey is this still open? i would add a preloader if thats what you want ?

**Comment by damcclean** [comment]
Yup, it's still free!

**Comment by Shaddamah** [comment]
@damcclean Is there any issue or new feature that I can work on? Would love to contribute!

**Comment by damcclean** [comment]
> @damcclean Is there any issue or new feature that I can work on? Would love to contribute!

This one's free: https://github.com/damcclean/hacktoberfest-finder/issues/187

**Comment by Shaddamah** [comment]
Thank you :)

**Comment by HayBeeCoder** [comment]
Can I still work on this?

**Comment by damcclean** [comment]
> Can I still work on this?

Sure!

**Comment by BetaHuhn** [comment]
Is it okay if I work on this too?
