### ISSUE TITLE
Use new TailwindCSS Purge feature

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#189]
It would be nice if we could use [Tailwind's new PurgeCSS feature](https://tailwindcss.com/docs/controlling-file-size#purging-specific-layers) so we can give the browser the smallest CSS file possible to render the page.

**Comment by AbhinavReddy-Dev** [comment]
Can I work on this?

**Comment by AbhinavReddy-Dev** [comment]
I have also found a couple styling issues on mobile version, I’ll make those changes as well.

**Comment by damcclean** [comment]
Awesome! Sure, go ahead!

**Comment by AbhinavReddy-Dev** [comment]
Great!, can you assign this to me so that others who come here will know about it?

**Comment by AbhinavReddy-Dev** [comment]
Hey, If you're going to merge the PR then add the following label "hacktoberfest-accepted".

**Comment by damcclean** [comment]
Implemented in #197.
