### ISSUE TITLE
Add view more button at the bottom of the issues list

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#19]

**Comment by nsrivastava645** [comment]
Can you please be specific where you want that button to be?

**Comment by damcclean** [comment]
[https://cdn-std.dprcdn.net/files/acc_635918/SECDDN](https://cdn-std.dprcdn.net/files/acc_635918/SECDDN)

@nsrivastava645

**Comment by shad-k** [comment]
@damcclean, I'd like to pick this up if not already assigned.

**Comment by lucas-barros** [comment]
I made a PR for this, here is the preview: https://deploy-preview-21--hacktoberfest-finder.netlify.com/
