### ISSUE TITLE
Add colour hierarchy to Issue Cards 

### ISSUE THREAD

**Issue by AbhinavReddy-Dev** [damcclean/hacktoberfest-finder#198]
I think it would be good to have colour hierarchy to let the user differentiate between the Issue, repo name and comments with black, teal and grey.

Something like this 

![Screenshot 2020-10-04 at 14 06 50](https://user-images.githubusercontent.com/33514341/95010972-dc66c000-064a-11eb-9122-ac3050ad8919.png)

Or we could stick to gray palette

![Screenshot 2020-10-04 at 14 14 05](https://user-images.githubusercontent.com/33514341/95011086-df15e500-064b-11eb-8a9d-0d34a196e812.png)

**Comment by damcclean** [comment]
I quite like the green!

**Comment by AbhinavReddy-Dev** [comment]
Cool, I'll make a PR once purgeCSS PR is approved.

**Comment by AbhinavReddy-Dev** [comment]
I am waiting for the "go to top" button merge to make this PR.

**Comment by damcclean** [comment]
Implemented in #200.
