### ISSUE TITLE
Add repository name to cards

### ISSUE THREAD

**Issue by dnguneratne** [damcclean/hacktoberfest-finder#20]
It would be nice to either have the repository owner / repository name, or just the repository name on each card.
Something like this;
![image](https://user-images.githubusercontent.com/8231763/46445948-6ff91380-c747-11e8-8d18-1649b7d32ff5.png)
It will match the card title font and we can place it either in the middle or off to a side.

I would like to work on this issue.

**Comment by damcclean** [comment]
Sure, you can work on this 👍 @dnguneratne
