### ISSUE TITLE
Ensure all 2020 contributors are in CONTRIBUTORS.md

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#202]
I think during the start of this year, I may have forgotten to double check that contributors added themselves to the `CONTRIBUTORS.md` file.

Ideally, I'd love someone to go through the merged pull requests and ensure they are linked to in the file. 

Thanks

**Comment by Jeremy-Walton** [comment]
I looked through and everyone that contributed this year is listed in the file. Unless you want to also link to the PR(s) they contributed, it should be fine as is.

**Comment by damcclean** [comment]
Cool, thanks for checking!
