### ISSUE TITLE
Take into account updated Hacktoberfest Rules

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#203]
It would be nice if we could only display issues on repositories which meet the updated rules and requirements of Hacktoberfest.

[See rule updates here](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by Kalovelo** [comment]
Hello, could I work on this issue for hacktoberfest2020? Thanks!

**Comment by damcclean** [comment]
> Hello, could I work on this issue for hacktoberfest2020? Thanks!

Sure!
