### ISSUE TITLE
Filter newly created repositories

### ISSUE THREAD

**Issue by koppor** [damcclean/hacktoberfest-finder#204]
There are so many projects available. A finder should help finding really good ones (and not ones just for collecting a swag easily).

I checked the projects listed. Most of them are very new (3 days) and are playground projects. Examples:

- https://github.com/ACM-VIT/libground
- https://github.com/coderobe/callsite.jar

May I ask that your site only lists repositories created before 2020-09-01?

Maybe, the finder should list projects with 10 or more stars and/or more than 2 contributors?

**Comment by damcclean** [comment]
That sounds like a good idea. I'd rather not filter new repositories in case there are some legitimate repositories created recently that have Hacktoberfest issues.

However, I do feel like there should be some system of only displaying 'legit' repositories. Like you suggested, maybe filtering to only show issues on repositories with more than X stars and X contributors would be a good idea.

I've labeled this issue as `Hacktoberfest` for anyone to pick up this issue (implementing checks for stars and contributors), while following the [contributors guide](https://github.com/damcclean/hacktoberfest-finder/blob/master/CONTRIBUTING.md).

**Comment by koppor** [comment]
May I ask whether this was implemented? Could you link the PR or the commit? (For traceability) Otherwise, I ask for keeping the issue opened.
