### ISSUE TITLE
Add banner to top of page for Hacktoberfest Giveaway

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#207]
It would be nice if we could add a banner to the top of the Hacktoberfest Finder to advertise Digital Product Playbook's Hacktoberfest contest.

**Link to contest tweet:** [https://twitter.com/DigiPlaybook/status/1315620838901788672](https://twitter.com/DigiPlaybook/status/1315620838901788672)

**Example:**
Here's an example of the kind of design I'm looking for. This example is on [DO's Hacktoberfest site](https://hacktoberfest.digitalocean.com/).

![image](https://user-images.githubusercontent.com/19637309/95743729-1dce1f80-0c8a-11eb-8779-4a72078c9a16.png)

**Comment by mocno123** [comment]
Hi Dan 
Can I work on this please?

**Comment by damcclean** [comment]
> Hi Dan
> Can I work on this please?

Sure!
