### ISSUE TITLE
Fix bug where issue list is replicated

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#23]
On the site, the 'See More' button loads more issues from the GitHub API, however it seems to be loading the same issues.

**Comment by marcelorl** [comment]
im taking a look

**Comment by GeekAb** [comment]
I am working on something similar and have fix ready. @marcelorl you started working on it?

**Comment by Optarion** [comment]
Hope this fix it!

**Comment by marcelorl** [comment]
not at all

thanks for letting me know.

**Comment by damcclean** [comment]
Fixed in #24
