### ISSUE TITLE
Words inside < > are dropped.

### ISSUE THREAD

**Issue by GrosSacASac** [damcclean/hacktoberfest-finder#33]
I created an issue with hacktoberfest https://github.com/GrosSacASac/DOM99/issues/22

The title is `Add html <meta> description and <meta> keywords for website`

It shows up with  `<meta>` dropped
![meta dropped screenshot](https://user-images.githubusercontent.com/5721194/47015910-91e29500-d14e-11e8-8794-fa614299edc3.png)

**Comment by damcclean** [comment]
Looks easy enough to fix. All it would require is changing the title from using `v-html` to using `v-text`.
