### ISSUE TITLE
Use Hacktoberfest Font on Heading

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#35]
The official Hacktoberfest website [uses a font](https://d.pr/free/i/0LqOI8) for the heading. I would like that font to be used on the heading that says 'Hacktoberfest Issue Finder'.

**Comment by dharmadev108** [comment]
I'll do it :)

**Comment by damcclean** [comment]
Awesome! @dharmadev108

**Comment by damcclean** [comment]
Fixed in #36
