### ISSUE TITLE
Add text to footer

### ISSUE THREAD

**Issue by damcclean** [damcclean/hacktoberfest-finder#45]
In the footer where it says `Unofficial site created by Duncan McClean.` replace that with `Unofficial site created by Duncan McClean and contributors`, with a link on contributors to [this page](https://github.com/damcclean/hacktoberfest-finder/blob/master/CONTRIBUTORS.md).

**Comment by dickyw71** [comment]
I have started working this issue.

**Comment by damcclean** [comment]
Cool. Thanks @dickyw71 👍

**Comment by dickyw71** [comment]
PR opened, I goofed on the issue number in my branch name and commit message (14 instead of 45). Please let me know if that is a problem.

**Comment by damcclean** [comment]
It's fine!

**Comment by damcclean** [comment]
Added in #47
