### ISSUE TITLE
Ignoring the build files

### ISSUE THREAD

**Issue by blenderskool** [damcclean/hacktoberfest-finder#8]
As the app.js and app.css files are generated in the build process, I think this should not be in the git. Hence they can be added to the .gitignore file. Netlify takes care of the building of these files.

**Comment by damcclean** [comment]
Yeah, feel free to make these changes :)

**Comment by blenderskool** [comment]
Ok, I will implement this :slightly_smiling_face:

**Comment by damcclean** [comment]
Completed in #9
